### PR TITLE
Update GCD bars to show correct spellname

### PR DESCRIPTION
**Pull request by krazyito65**

### CODE REVIEW

**Comment by krazyito65** [comment]
Do you plan on trying to get this pushed to the main curse repo?

**Comment by voidzone** [comment]
Nope.  I don't have the Lua knowledge to properly maintain it.  Just created this branch as a quick and dirty update for myself.

**Comment by voidzone** [comment]
I did however create an issue on the main project so if the author wants to pull it into the main they can.

https://wow.curseforge.com/projects/gnosis/issues/100

**Comment by voidzone** [comment]
Spoke with the author and was given contributor access.  New version should be available via Twitch once it's approved.

**Comment by krazyito65** [comment]
Nice!

**Pull request merged**
